name: burningbros_productflow
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # HTTP client  
  dio: ^5.9.0

  # State management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Local storage
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1 # contains Isar Core
  path_provider: ^2.1.2

  # UI components
  cached_network_image: ^3.4.1
  fluttertoast: ^8.2.12
  easy_refresh: ^3.4.0

  # Data serialization
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.3.0
  freezed: ^2.4.5
  riverpod_generator: ^2.3.9
  json_serializable: ^6.7.1
  isar_generator: ^3.1.0+1

# Override dependencies to fix compatibility issues
dependency_overrides:
  source_gen: ^1.3.2
  analyzer: ^5.13.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true